---
title: "R Notebook"
output: pdf_document
---

````{r, setup, include=FALSE}
library(rugarch)
````

```{r}
setwd("..")
sp<-read.csv("Data/Processed/sp_logret_changepoint.csv")$x
ny<-read.csv("Data/Processed/ny_logret_changepoint.csv")$x
nas<-read.csv("Data/Processed/nas_logret_changepoint.csv")$x
```

```{r}
final.aic <- Inf
final.order <- c(0,0)
for (i in 1:4) for (j in 1:4) {
 sp_model <- ugarchspec(variance.model=list(garchOrder=c(i,j)),
             mean.model=list(armaOrder=c(1,0)), distribution.model = "std")
 current.aic <- infocriteria(ugarchfit(spec=sp_model,data=sp,solver='hybrid'))[1]
 if (current.aic < final.aic){
    final.aic <- current.aic
    final.order <- c(i,j)
  }
}
final.order
```

```{r}
final.aic <- Inf
final.order <- c(0,0)
for (i in 1:4) for (j in 1:4) {
 ny_model <- ugarchspec(variance.model=list(garchOrder=c(i,j)),
             mean.model=list(armaOrder=c(1,0)), distribution.model = "std")
 current.aic <- infocriteria(ugarchfit(spec=ny_model,data=ny,solver='hybrid'))[1]
 if (current.aic < final.aic){
    final.aic <- current.aic
    final.order <- c(i,j)
  }
}
final.order
```
```{r}
final.aic <- Inf
final.order <- c(0,0)
for (i in 1:4) for (j in 1:4) {
 nas_model <- ugarchspec(variance.model=list(garchOrder=c(i,j)),
             mean.model=list(armaOrder=c(1,0)), distribution.model = "std")
 current.aic <- infocriteria(ugarchfit(spec=nas_model,data=nas,solver='hybrid'))[1]
 if (current.aic < final.aic){
    final.aic <- current.aic
    final.order <- c(i,j)
  }
}

```

```{r}
sp_model <- ugarchspec(variance.model=list(garchOrder=c(3,1)),
             mean.model=list(armaOrder=c(1,0)), distribution.model = "std")
sp_fit <- ugarchfit(spec=sp_model,data=sp,solver='hybrid')
ug_var <- sp_fit@fit$var

ug_res2 <- (sp_fit@fit$residuals)^2

plot(ug_res2, type = "l")
lines(ug_var, col = "green")
```

```{r}
ugfore <- ugarchforecast(sp_fit, n.ahead = 10)
ugfore@forecast$sigmaFor
```

